plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'pkg/**/*'
    - 'test/app/**/*'
    - 'tmp/**/*'

# Layout cops
Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/**/*'

# Style cops
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/IdenticalConditionalBranches:
  Exclude:
    - 'test/**/*'

# Metrics cops
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - '*.gemspec'
    - 'Rakefile'
    - 'lib/capistrano/tasks/**/*'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'
    - 'lib/capistrano/tasks/**/*'
    - 'lib/capistrano/sidekiq.rb'
    - 'lib/capistrano/sidekiq/systemd.rb'

Minitest/MultipleAssertions:
  Max: 15

# Minitest cops
Minitest/AssertEmptyLiteral:
  Enabled: true

Minitest/AssertTruthy:
  Enabled: true

Minitest/RefuteFalse:
  Enabled: true

# Rake cops
Rake/Desc:
  Enabled: false

Rake/MethodDefinitionInTask:
  Enabled: false

# Naming cops
Naming/FileName:
  Exclude:
    - 'lib/capistrano-sidekiq.rb'

# Gemspec cops
Gemspec/DevelopmentDependencies:
  Enabled: false

# Lint cops
Lint/MissingSuper:
  Exclude:
    - 'lib/capistrano/**/*'

Lint/EmptyFile:
  Exclude:
    - 'lib/capistrano-sidekiq.rb'

Lint/DuplicateBranch:
  Exclude:
    - 'test/**/*'