name: Run Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          
      - name: Run Rake Task
        run: bundle exec rake

      - name: Upload Capistrano log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: capistrano-log-${{ matrix.ruby-version }}
          path: test/log/*.log