name: Run Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rake:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          
      - name: Run RuboCop
        run: bundle exec rubocop
        
      - name: Run Tests
        run: bundle exec rake test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.ruby-version }}
          path: |
            test/log/*.log
            test/*.log
